"""Backend-neutral contracts and persistence for direct child agents."""

from .contracts import (
    ACTIVE_AGENT_STATES,
    ALLOWED_AGENT_STATE_TRANSITIONS,
    TERMINAL_AGENT_STATES,
    AgentContractError,
    AgentEvent,
    AgentHandle,
    AgentResult,
    AgentSpec,
    AgentState,
    Budget,
    InvalidStateTransition,
    coerce_agent_state,
    context_hash,
    require_agent_state_transition,
    utc_now,
)
from .event_store import (
    AgentReconciliation,
    EventStore,
    EventStoreCorruptionError,
    EventStoreError,
    EventStoreLockTimeout,
    EventSequenceConflictError,
    IdempotencyConflictError,
    JsonlEventStore,
    SnapshotConflictError,
)
from .codex_team_tracker import CodexTeamRuntimeTracker
from .run_metrics import (
    RUN_METRICS_SCHEMA,
    RUN_STAGE_METRIC_SCHEMA,
    RunMetricsRecorder,
    current_run_metrics,
    measure_current_stage,
    record_run_metrics,
    run_metric_checkpoint,
    run_metric_stage,
    validate_run_metrics,
)
from .artifact_store import (
    ARTIFACT_GC_PLAN_SCHEMA,
    ARTIFACT_POINTER_SCHEMA,
    ARTIFACT_REF_SCHEMA,
    ArtifactCorruptionError,
    ArtifactRef,
    ArtifactReferenceError,
    ArtifactStore,
    ArtifactStoreError,
)
from .run_index import (
    RUN_INDEX_SCHEMA,
    RUN_MANIFEST_SCHEMA,
    RunIndex,
    RunIndexError,
)
from .run_storage import (
    RUN_STORAGE_PUBLISH_SCHEMA,
    RUN_STORAGE_REBUILD_SCHEMA,
    publish_run_projection,
    rebuild_run_index,
    run_storage_object_stats,
)
from .credentials import Credential, resolve_codex_credential
from .paths import RuntimePaths


__all__ = [
    "ACTIVE_AGENT_STATES",
    "ALLOWED_AGENT_STATE_TRANSITIONS",
    "TERMINAL_AGENT_STATES",
    "AgentContractError",
    "AgentEvent",
    "AgentHandle",
    "AgentReconciliation",
    "AgentResult",
    "AgentSpec",
    "AgentState",
    "ARTIFACT_GC_PLAN_SCHEMA",
    "ARTIFACT_POINTER_SCHEMA",
    "ARTIFACT_REF_SCHEMA",
    "ArtifactCorruptionError",
    "ArtifactRef",
    "ArtifactReferenceError",
    "ArtifactStore",
    "ArtifactStoreError",
    "Budget",
    "CodexTeamRuntimeTracker",
    "Credential",
    "EventStore",
    "EventStoreCorruptionError",
    "EventStoreError",
    "EventStoreLockTimeout",
    "EventSequenceConflictError",
    "IdempotencyConflictError",
    "InvalidStateTransition",
    "JsonlEventStore",
    "RUN_METRICS_SCHEMA",
    "RUN_STAGE_METRIC_SCHEMA",
    "RUN_INDEX_SCHEMA",
    "RUN_MANIFEST_SCHEMA",
    "RUN_STORAGE_PUBLISH_SCHEMA",
    "RUN_STORAGE_REBUILD_SCHEMA",
    "RunIndex",
    "RunIndexError",
    "RunMetricsRecorder",
    "RuntimePaths",
    "SnapshotConflictError",
    "coerce_agent_state",
    "context_hash",
    "current_run_metrics",
    "publish_run_projection",
    "rebuild_run_index",
    "measure_current_stage",
    "record_run_metrics",
    "require_agent_state_transition",
    "resolve_codex_credential",
    "run_metric_checkpoint",
    "run_metric_stage",
    "run_storage_object_stats",
    "utc_now",
    "validate_run_metrics",
]
