"""Pluggable provider contracts for the AutoPlanner mainline."""
from cascade_planner.providers.contracts import (
    AgentBackendProvider,
    ArtifactStoreProvider,
    EvidenceProvider,
    ExperimentExecutorProvider,
    ProposalProvider,
    Provider,
    ProviderContext,
    ProviderDescriptor,
    ProviderKind,
    ProviderResultEnvelope,
    RendererProvider,
    StockProvider,
    VerifierProvider,
    validate_provider_result,
)
from cascade_planner.providers.registry import (
    ProviderRegistry,
    ProviderRegistryError,
    descriptor_from_dict,
)
from cascade_planner.providers.stock import (
    BenchmarkCatalogStockProvider,
    canonicalize_stock_snapshot,
    SnapshotStockProvider,
    stock_snapshot_sha256,
    StockBoundary,
    StockOffer,
)
from cascade_planner.providers.builtins import (
    ChemEnzyProposalProvider,
    LiteratureEvidenceProvider,
    ReactionRouteVerifierProvider,
    build_default_provider_registry,
)
from cascade_planner.providers.experiment import (
    EXPERIMENT_DISPATCH_HANDOFF_SCHEMA,
    EXPERIMENT_EXECUTOR_POLICY_SCHEMA,
    ExperimentExecutorPolicyError,
    ManualExperimentExecutorProvider,
    select_experiment_executor,
    validate_experiment_dispatch_handoff,
)

__all__ = [
    "AgentBackendProvider",
    "ArtifactStoreProvider",
    "EvidenceProvider",
    "ExperimentExecutorProvider",
    "ProposalProvider",
    "Provider",
    "ProviderContext",
    "ProviderDescriptor",
    "ProviderKind",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderResultEnvelope",
    "RendererProvider",
    "StockProvider",
    "BenchmarkCatalogStockProvider",
    "SnapshotStockProvider",
    "canonicalize_stock_snapshot",
    "stock_snapshot_sha256",
    "StockBoundary",
    "StockOffer",
    "VerifierProvider",
    "descriptor_from_dict",
    "validate_provider_result",
    "ChemEnzyProposalProvider",
    "LiteratureEvidenceProvider",
    "ReactionRouteVerifierProvider",
    "build_default_provider_registry",
    "EXPERIMENT_DISPATCH_HANDOFF_SCHEMA",
    "EXPERIMENT_EXECUTOR_POLICY_SCHEMA",
    "ExperimentExecutorPolicyError",
    "ManualExperimentExecutorProvider",
    "select_experiment_executor",
    "validate_experiment_dispatch_handoff",
]
