"""Pluggable provider contracts for the AutoPlanner mainline."""
from cascade_planner.providers.contracts import (
    AgentBackendProvider,
    ArtifactStoreProvider,
    EvidenceProvider,
    ProposalProvider,
    Provider,
    ProviderContext,
    ProviderDescriptor,
    ProviderKind,
    ProviderResultEnvelope,
    RendererProvider,
    StockProvider,
    VerifierProvider,
    validate_provider_result,
)
from cascade_planner.providers.registry import (
    ProviderRegistry,
    ProviderRegistryError,
    descriptor_from_dict,
)
from cascade_planner.providers.stock import (
    BenchmarkCatalogStockProvider,
    canonicalize_stock_snapshot,
    SnapshotStockProvider,
    stock_snapshot_sha256,
    StockBoundary,
    StockOffer,
)
from cascade_planner.providers.builtins import (
    ChemEnzyProposalProvider,
    CodexRetrosynthesisProvider,
    LiteratureEvidenceProvider,
    ReactionRouteVerifierProvider,
    build_default_provider_registry,
)

__all__ = [
    "AgentBackendProvider",
    "ArtifactStoreProvider",
    "EvidenceProvider",
    "ProposalProvider",
    "Provider",
    "ProviderContext",
    "ProviderDescriptor",
    "ProviderKind",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderResultEnvelope",
    "RendererProvider",
    "StockProvider",
    "BenchmarkCatalogStockProvider",
    "SnapshotStockProvider",
    "canonicalize_stock_snapshot",
    "stock_snapshot_sha256",
    "StockBoundary",
    "StockOffer",
    "VerifierProvider",
    "descriptor_from_dict",
    "validate_provider_result",
    "CodexRetrosynthesisProvider",
    "ChemEnzyProposalProvider",
    "LiteratureEvidenceProvider",
    "ReactionRouteVerifierProvider",
    "build_default_provider_registry",
]
