"""Cascade-native search-state, failure, repair, and search contracts."""
import importlib
from cascade_planner.cascade_search.cost import (
    CascadeCostBreakdown,
    CascadeCostWeights,
    score_cascade_state,
)
from cascade_planner.cascade_search.condition_state import (
    ConditionStateReport,
    StageConditionSummary,
    summarize_condition_state,
)
from cascade_planner.cascade_search.failure import (
    annotate_state_failures,
    detect_cascade_failures,
)
from cascade_planner.cascade_search.interfaces import (
    CascadeCofactorClosureModelProtocol,
    CascadeConditionTransitionModelProtocol,
    CascadeEnzymeModuleRankerProtocol,
    CascadeFailureDetector,
    CascadeProposalProvider,
    CascadeRepairPlanner,
    CascadeSearchController,
    CascadeActionValueModelProtocol,
    CascadePairScorerProtocol,
    CascadeSourcePolicyProtocol,
    CascadeTransitionValueModelProtocol,
    CascadeValueModelProtocol,
)
from cascade_planner.cascade_search.proposals import (
    CascadeRetrievalProposalProvider,
    CascadeSubgoalEvidenceProvider,
    ChemEnzyProposalProvider,
    ChemicalTemplateProposalProvider,
    ProposalDiagnostics,
    ProposalRequest,
    RetroChimeraProposalProvider,
    RouteTreeProposalProvider,
    StaticProposalProvider,
    TemplateRelevanceProposalProvider,
    coerce_to_cascade_action,
    route_step_candidate_to_action,
)
from cascade_planner.cascade_search.action_value import (
    LoadedCascadeActionValueModel,
    SubgoalHintActionScorer,
)
from cascade_planner.cascade_search.pair_scorer import (
    LearnedCascadePairScorer,
    PAIR_LABEL_NAMES,
    RuleCascadePairScorer,
    CascadePairScore,
    adjacent_downstream_step,
    build_pair_feature_schema,
    pair_feature_vector,
    pair_payload_from_steps,
    pair_rule_features,
)
from cascade_planner.cascade_search.repair import (
    CascadeRepairPolicy,
    CascadeRepairRule,
)
from cascade_planner.cascade_search.search import (
    CascadeProgramSearch,
    CascadeSearchConfig,
    CascadeSearchResult,
    CascadeSearchStats,
    apply_cascade_action,
    default_cascade_search_controller,
    plan_cascade_program,
)
from cascade_planner.cascade_search.trace import (
    CascadeSearchTraceEvent,
    CascadeTraceCollector,
    TRACE_SCHEMA_VERSION,
)
from cascade_planner.cascade_search.transition_value import (
    CascadeTransitionValueNetwork,
    CascadeTransitionValuePrediction,
    LoadedCascadeTransitionValueModel,
    TRANSITION_FAILURE_KINDS,
    TRANSITION_SCALAR_FEATURES,
    transition_child_summary,
    transition_feature_dim,
    transition_feature_vector,
    transition_reward,
)
V4_ROUTE_LABEL_NAMES = [
    "gold_quality",
    "demonstrated_success",
    "outcome_supported",
    "condition_supported",
    "substrate_scope_supported",
    "rxn_step_supported",
    "catalyst_supported",
    "species_supported",
]

_V4_PRODUCT_VALUE_EXPORTS = {
    "LoadedV4CascadeProductValue",
    "V4CascadeProductValueNetwork",
    "V4RoutePrediction",
    "build_route_feature_schema",
    "observable_value_target",
    "route_feature_vector",
    "route_label_vector",
    "route_record_from_native_route",
    "route_record_from_trace_candidate",
    "route_record_from_v4",
}


def __getattr__(name: str):
    if name in _V4_PRODUCT_VALUE_EXPORTS:
        module = importlib.import_module("cascade_planner.cascade_search.v4_product_value")
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(name)

from cascade_planner.cascade_search.state import (
    CascadeAction,
    CascadeActionType,
    CascadeFailure,
    CascadeFailureKind,
    CascadeModule,
    CascadeProgramState,
    CascadeSearchState,
    CofactorLedger,
    ConditionEnvelope,
    RedoxLedger,
    Stage,
    StageGraph,
    StageTransition,
    StepAnnotation,
)
from cascade_planner.cascade_search.value import (
    CascadeSourcePolicy,
    CascadeValuePrediction,
    CofactorClosureModel,
    CofactorClosurePrediction,
    ConditionTransitionModel,
    ConditionTransitionPrediction,
    EnzymeModuleRanker,
    HeuristicCascadeValueModel,
    LearnedCascadeValueModel,
    LoadedLearnedVerifierValueModel,
    RuleCascadeValueModel,
    SourceBudget,
    VerifierAugmentedCascadeValueModel,
)

__all__ = [
    "CascadeAction",
    "CascadeActionValueModelProtocol",
    "CascadeActionType",
    "CascadeSearchTraceEvent",
    "CascadeCofactorClosureModelProtocol",
    "CascadeConditionTransitionModelProtocol",
    "CascadeCostBreakdown",
    "CascadeCostWeights",
    "ConditionStateReport",
    "CascadeEnzymeModuleRankerProtocol",
    "CascadeFailure",
    "CascadeFailureDetector",
    "CascadeFailureKind",
    "CascadeModule",
    "CascadeProposalProvider",
    "CascadeRetrievalProposalProvider",
    "CascadeSubgoalEvidenceProvider",
    "CascadeProgramSearch",
    "CascadeProgramState",
    "CascadePairScore",
    "CascadePairScorerProtocol",
    "CascadeRepairPlanner",
    "CascadeRepairPolicy",
    "CascadeRepairRule",
    "CascadeSearchConfig",
    "CascadeSearchController",
    "CascadeSearchResult",
    "CascadeSearchState",
    "CascadeSearchStats",
    "CascadeTraceCollector",
    "CascadeSourcePolicy",
    "CascadeSourcePolicyProtocol",
    "CascadeTransitionValueModelProtocol",
    "CascadeTransitionValueNetwork",
    "CascadeTransitionValuePrediction",
    "CascadeValuePrediction",
    "VerifierAugmentedCascadeValueModel",
    "LoadedLearnedVerifierValueModel",
    "CascadeValueModelProtocol",
    "ChemEnzyProposalProvider",
    "ChemicalTemplateProposalProvider",
    "CofactorClosureModel",
    "CofactorClosurePrediction",
    "CofactorLedger",
    "ConditionEnvelope",
    "ConditionTransitionModel",
    "ConditionTransitionPrediction",
    "EnzymeModuleRanker",
    "HeuristicCascadeValueModel",
    "LearnedCascadeValueModel",
    "LearnedCascadePairScorer",
    "LoadedCascadeActionValueModel",
    "LoadedCascadeTransitionValueModel",
    "LoadedV4CascadeProductValue",
    "ProposalDiagnostics",
    "ProposalRequest",
    "RedoxLedger",
    "RetroChimeraProposalProvider",
    "RouteTreeProposalProvider",
    "RuleCascadePairScorer",
    "RuleCascadeValueModel",
    "SourceBudget",
    "Stage",
    "StageGraph",
    "StageTransition",
    "StaticProposalProvider",
    "StepAnnotation",
    "StageConditionSummary",
    "SubgoalHintActionScorer",
    "TemplateRelevanceProposalProvider",
    "TRACE_SCHEMA_VERSION",
    "TRANSITION_FAILURE_KINDS",
    "TRANSITION_SCALAR_FEATURES",
    "PAIR_LABEL_NAMES",
    "V4_ROUTE_LABEL_NAMES",
    "V4CascadeProductValueNetwork",
    "V4RoutePrediction",
    "annotate_state_failures",
    "apply_cascade_action",
    "adjacent_downstream_step",
    "build_pair_feature_schema",
    "build_route_feature_schema",
    "coerce_to_cascade_action",
    "default_cascade_search_controller",
    "detect_cascade_failures",
    "observable_value_target",
    "pair_feature_vector",
    "pair_payload_from_steps",
    "pair_rule_features",
    "plan_cascade_program",
    "route_feature_vector",
    "route_label_vector",
    "route_record_from_native_route",
    "route_record_from_trace_candidate",
    "route_record_from_v4",
    "route_step_candidate_to_action",
    "score_cascade_state",
    "summarize_condition_state",
    "transition_child_summary",
    "transition_feature_dim",
    "transition_feature_vector",
    "transition_reward",
]
